### PR TITLE
Map code

### PR DESCRIPTION
**Pull request by ethteck**

### CODE REVIEW

**Comment by nanaian** [comment]
:sunglasses:

**Review by ethteck — COMMENTED** [review]
I think the 3445th file we included is wrong...redo everything

**Comment by ethteck** [comment]
sorry for the squalsh but thanks to @nanaian for a great addition to the project and @pixel-stuck for helping fix a bug at the end

**Comment by nanaian** [comment]
```sh
/usr/src/papermario $ ./coverage.py 
757+22 / 10458 functions (7.24% matched)
```

**Pull request merged**
